export const UPLOAD_PRESENTATION = 'UPLOAD_PRESENTATION';
export const UPLOAD_PRESENTATION_SUCCESS = 'UPLOAD_PRESENTATION_SUCCESS';

export const GET_PRESENTATION = 'GET_PRESENTATION';
export const GET_PRESENTATION_SUCCESS = 'GET_PRESENTATION_SUCCESS';

export const INCREMENT_CURRENT_SLIDE = 'INCREMENT_CURRENT_SLIDE';
export const DECREMENT_CURRENT_SLIDE = 'DECREMENT_CURRENT_SLIDE';
export const SET_CURRENT_SLIDE_SUCCESS = 'SET_CURRENT_SLIDE_SUCCESS';

export const REMOVE_PRESENTATION = 'REMOVE_PRESENTATION';
export const REMOVE_PRESENTATION_SUCCESS = 'REMOVE_PRESENTATION_SUCCESS';
