const UPLOAD_PRESENTATION = 'UPLOAD_PRESENTATION';
const UPLOAD_PRESENTATION_SUCCESS = 'UPLOAD_PRESENTATION_SUCCESS';

const GET_PRESENTATION = 'GET_PRESENTATION';
const GET_PRESENTATION_SUCCESS = 'GET_PRESENTATION_SUCCESS';

const INCREMENT_CURRENT_SLIDE = 'INCREMENT_CURRENT_SLIDE';
const DECREMENT_CURRENT_SLIDE = 'DECREMENT_CURRENT_SLIDE';
const SET_CURRENT_SLIDE_SUCCESS = 'SET_CURRENT_SLIDE_SUCCESS';

const REMOVE_PRESENTATION = 'REMOVE_PRESENTATION';
const REMOVE_PRESENTATION_SUCCESS = 'REMOVE_PRESENTATION_SUCCESS';
